# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                node-version: [18.15.0]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - name: Checkout source code. #CI서버로 내려받은 후 특정 브랜치로 전환
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }} #노드 버전에 맞게 설치
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Check Npm -v
              run: npm -v

            - name: Set Secrets to Env
              run: |
                  # secrets 목록
                  secrets=(
                    API_LIMIT_SECOND
                    API_LIMIT_TIMES
                    AUTH_QUERY_SECRET_KEY
                    AWS_ACCESS_KEY_ID
                    AWS_SECRET_ACCESS_KEY
                    COMMON_FILE_URL
                    COOKIE_SECRET
                    DEFAULT_PROFILE_IMAGE
                    EMAIL_AUTH_DOMAIN
                    JWT_ACCESS_TOKEN_EXPIRESIN
                    JWT_REFRESH_TOKEN_EXPIRESIN
                    JWT_SECRET
                    JWT_SIGN_ALGORITHM
                    MONGODB_IP
                    PASSWORD_SALT_OR_ROUNDS
                    RDS_HOST
                    RDS_PASSWORD
                    RDS_USERNAME
                    REDIS_PORT
                    S3_BUCKET
                    S3_REGION
                    SES_AWS_ACCESS_KEY
                    SES_AWS_ACCESS_KEY_ID
                    SMU_STUDENT_EMAIL_DOMAIN
                  )

                  # .env 파일 작성
                  for secret in "${secrets[@]}"
                  do
                    echo "${secret}=${{ secrets.${secret} }}" >> .env
                  done

            - name: Check .env file
              run: cat .env

            - name: build server files #필ㄹ요한 dependency들을 설치하고 빌드
              working-directory: ./
              run: |
                  npm i
                  npm run build

            - name: zip file
              run: zip -r smus.zip ./dist ./scripts ./appspec.yml ./.env ./package.json

            - name: AWS configure credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-northeast-2

            - name: upload to S3
              run: aws s3 cp --region ap-northeast-2 ./smus.zip s3://smus/BE

            - name: deploy with AWS codeDeploy
              run: aws deploy create-deployment
                  --application-name smus-cd
                  --deployment-config-name CodeDeployDefault.OneAtATime
                  --deployment-group-name smus-cdg
                  --s3-location bucket=smus,bundleType=zip,key=BE/smus.zip
